---
- become: true
  block:
  - name: Install moby (docker)
    package:
      name: moby-engine
      state: present

  - name: Start moby (docker)
    systemd:
      name: docker
      state: started
      enabled: true

  - name: Add user to docker group
    user:
      name: "{{ ansible_ssh_user }}"
      groups: docker
      append: true

  - name: Reset connection to pick up new group
    meta: reset_connection

  - name: Install pip
    package:
      name: python3-pip
      state: present

  - name: Install Docker SDK
    pip:
      name: docker
      state: present
